[features]
seeds = false
#[programs.localnet]
#token_delegate = "821i9RWA8xc5nN2i4MA4AsGRqqXx68qCVEi4YVkcWHpE"
[programs.devnet]
token_delegate = "821i9RWA8xc5nN2i4MA4AsGRqqXx68qCVEi4YVkcWHpE"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/Users/steviesh/.config/solana-keypairs/keypair.json"

[scripts]
# must set browser environment to empty
test = "yarn run jest"
