[features]
seeds = false
[programs.localnet]
token_delegate = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/Users/steviesh/.config/solana-keypairs/keypair.json"

[scripts]
test = "yarn run jest"
